blog/urls.py
from django.urls import path, include
from blog.apps import BlogConfig
from blog.views import  BlogListView, BlogCreateView,BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('blog_form', BlogCreateView.as_view(), name='create'),
    path('blog_form/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='confirm_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    header = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(blank=True, null=True, max_length=100, verbose_name='Ссылка')
    content = models.TextField(blank=True, null=True, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    published = models.BooleanField(default=False, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Счетчик просмотров')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

    def __str__(self):
        return f'{self.header}'
# Create your models here.

blog/forms.py
from django import forms

from blog.models import Blog
from catalog.forms import StyleFormMixin



class BlogForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Blog
        fields = '__all__'

blog/views.py
from django.shortcuts import render

from blog.models import Blog
from django import template
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from pytils.translit import slugify
from django.core.mail import send_mail
from blog.forms import BlogForm

class BlogListView(ListView):
    model = Blog
    extra_context = {'title': 'Список блогов'}

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(published=True)

        return queryset


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blogs')
    extra_context = {'title': 'Добавление блога'}

    def form_valid(self, form):
        new_blog = form.save()
        new_blog.slug = slugify(new_blog.header)
        new_blog.save()

        return super().form_valid(form)

class BlogDetailView(DetailView):
    model = Blog
    fields = '__all__'
    extra_context = {'title': 'Блог'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        if self.object.views_count == 100:
            subject = f'{self.object.header} - очень популярный блог'
            message = f'Количество просмотров блога {self.object.header} превысило 100'
            from_email = 'djangopost@yandex.ru'
            recipient_list = ['avgl@mail.ru']
            send_mail(subject, message, from_email, recipient_list,fail_silently=False)

        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    success_url = reverse_lazy('blog:blogs')
    extra_context = {'title': 'Изменение блога'}

    def form_valid(self, form):
        new_blog = form.save()
        new_blog.slug = slugify(new_blog.header)
        new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs')
    extra_context = {'title': 'Удаление блога'}

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-4 mb-3 mb-sm-0">

    <div class="card">
        <div class="card-body">

            <form method="post">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить блог "{{ object.header }}"?</p>

                <button type="submit" class="btn btn-danger">Подтверждаю</button>
                <a href="{% url 'blog:blogs' %}" class="btn btn-warning">Отменить</a>

                <br>
            </form>
        </div>

    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.header }}</h4>
        </div>
        <div class="card-body">
            <p> Просмотры: {{ object.views_count }}</p>
            <p><em>{{ object.slug }}</em></p>
            <p>{{ object.content }}</p>
        </div>
    </div>
    <div class="col-6 px-3 py-3 pt-md-3 pb-md-4">
        <img src="/media/{{ object.preview }}" width="150"/>
    </div>

    <br>
    <a href="{% url 'blog:blogs' %}" class="btn btn-outline-success">Вернуться в список блогов</a>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                        Сохранить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
            </form>

        </div>
    </div>
</div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<dev>
    <h2 class="my-0 px-3 py-3 pt-md-3 pb-md-4 mr-md-auto font-weight-normal">Блоги</h2>
</dev>

{% for object in object_list %}

<div class="col-sm-4 mb-3 mb-sm-3">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ object.header }}</h4>
            <p class="card-text">{{ object.slug }}</p>
            <p class="card-text">Просмотры: {{ object.views_count }}</p>
            <br>
            <a class="btn btn-outline-success" href="{% url 'blog:detail' object.pk %}">Подробнее</a>
            {% if user.is_authenticated %}
            <a class="btn btn-warning" href="{% url 'blog:update' object.pk %}">Изменить</a>
            <a class="btn btn-danger" href="{% url 'blog:confirm_delete' object.pk %}">Удалить</a>
            {% endif %}
            <br>
        </div>
    </div>
</div>

{% endfor %}

{% if user.is_authenticated %}
<div>
    <br> <br>
    <a class="btn btn-success" href="blog_form">Создать новую запись в блоге</a>
</div>
{% endif %}
{% endblock %}