blog/urls.py
from django.urls import path, include
from blog.apps import BlogConfig
from blog.views import  BlogListView, BlogCreateView,BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('blog_form', BlogCreateView.as_view(), name='create'),
    path('blog_form/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='confirm_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, ProfileView, email_verification, ResetPasswordView, UserDoesNotFound
from users.apps import UsersConfig


app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('pass_reset/', ResetPasswordView.as_view(), name='pass_reset'),
    path('user_does_not_found/', UserDoesNotFound.as_view(), name='user_does_not_found'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, blank=True, null=True, verbose_name='телефон')
    country = models.CharField(max_length=50, blank=True, null=True, verbose_name='страна')
    avatar = models.ImageField(upload_to='users/', blank=True, null=True, verbose_name='аватар')

    token = models.CharField(max_length=100, blank=True, null=True, verbose_name='токен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms
from catalog.forms import StyleFormMixin

class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model =User
        fields = ('email', 'first_name', 'last_name', 'avatar')



class UserPasswordRecoveryForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

users/views.py
import secrets
import string

from django import forms
from django.http import request
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, UserPasswordRecoveryForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'Регистрация'}

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(subject='Подтверждение почты',
                  message=f'Пожалуйста подтверди корректность почтового адреаса {url}',
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email]
                  )

        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))

class ResetPasswordView(TemplateView):
    model = User
    form_class = PasswordResetForm
    template_name = 'users/pass_reset.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'Смена пароля'}

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_pass = User.objects.make_random_password(length=10)
            send_mail(
                subject='Новый пароль',
                message=f'Ваш новый пароль: {new_pass}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
            user.set_password = make_password(new_pass, salt=None, hasher='default')
            user.save()
            return redirect(reverse('users:login'))
        except User.DoesNotExist:
            return redirect(reverse('users:user_does_not_found'))


class UserDoesNotFound(TemplateView):
    model=User
    template_name = 'users/user_does_not_found.html'
    extra_context = {'title': 'Смена пароля'}


class ProfileView(UpdateView):
    extra_context = {'title': 'Профиль'}
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">

            <h4 class="card-title">
                Вход
            </h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    Войти
                </button>
                <a class="btn btn-outline-success" href="{% url 'users:pass_reset' %}">
                    Восстановить пароль
                </a>

            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/pass_reset.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">

            <h4 class="card-title">
                Вход
            </h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="form-label">
                        Введите Email и мы вышлем вам новый пароль
                    </label>
                    <input type="email" name="email" class="form-control mb-3" placeholder="Email">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">
                            Восстановить пароль
                        </button>
                    </div>
            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">

            <h4 class="card-title">
                Регистрация
            </h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/user_does_not_found.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">
                Пользователь с таким адресом в системе не зарегистрирован
            </h4>

        </div>
        <div class="card-body">

            <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                <div class="text-left">
                    <a class="btn btn-outline-success" href="{% url 'users:pass_reset' %}">Попробовать снова</a>
                    <a class="btn btn-outline-success" href="{% url 'users:register' %}">Зарегистрироваться</a>
                </div>
            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">

            <h4 class="card-title">
                Профиль
            </h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}