blog/urls.py
from django.urls import path, include
from blog.apps import BlogConfig
from blog.views import  BlogListView, BlogCreateView,BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blogs'),
    path('blog_form', BlogCreateView.as_view(), name='create'),
    path('blog_form/<int:pk>', BlogUpdateView.as_view(), name='update'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='confirm_delete'),
]

catalog/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from catalog.apps import NewappConfig
from catalog.views import ProductListView, ProductDetailView, ContactCreateView, ProductCreateView, ProductUpdateView, CategoryListView

app_name = NewappConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', ContactCreateView.as_view(), name='contacts'),
    path('products/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    header = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(blank=True, null=True, max_length=100, verbose_name='Ссылка')
    content = models.TextField(blank=True, null=True, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    published = models.BooleanField(default=False, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Счетчик просмотров')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

    def __str__(self):
        return f'{self.header}'
# Create your models here.

catalog/models.py
from django.db import models
from users.models import User


# Create your models here.
class Category(models.Model):
    # objects = None
    category_name = models.CharField(max_length=100, verbose_name='Наименование категории')
    category_description = models.CharField(max_length=500, verbose_name='Описание категории')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=500, verbose_name='Описание')
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    price = models.IntegerField(verbose_name='Цена за покупку')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (записи в БД)')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения (записи в БД)')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ('can_change_publication_status', 'can change publication status'),
            ('can_change_description', 'can change description'),
            ('can_change_category', 'can change category')
        ]

    def __str__(self):
        return f'{self.name}'


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя контакта')
    phone = models.CharField(max_length=50, blank=True, null=True, verbose_name='Телефон')
    email = models.CharField(max_length=50, blank=True, null=True, verbose_name='Почта')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(Product,on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Продукт')
    version_number = models.IntegerField(default=1, verbose_name='Номер версии')
    version_name = models.CharField(max_length=150, verbose_name='Название версии')
    actual_version = models.BooleanField(default=False,verbose_name='Признак текущей версии')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return f'{self.version_number} - {self.version_name}'

catalog/forms.py
from django import forms
from django.forms import BooleanField
from catalog.models import Product, Contact, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

class ProductForm(StyleFormMixin,forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        clean_data = self.cleaned_data['name']
        clean_data_words = clean_data.split()
        bad_words = ['казино',
                     'криптовалюта',
                     'крипта',
                     'биржа',
                     'дешево',
                     'бесплатно',
                     'обман',
                     'полиция',
                     'радар']

        for word in clean_data_words:
            if word.lower() in bad_words:
                raise forms.ValidationError(f'Слово {word} не может содержаться в названии продукта')

        return clean_data

    def clean_description(self):
        clean_data = self.cleaned_data['description']
        clean_data_words = clean_data.split()
        bad_words = ['казино',
                     'криптовалюта',
                     'крипта',
                     'биржа',
                     'дешево',
                     'бесплатно',
                     'обман',
                     'полиция',
                     'радар']

        for word in clean_data_words:
            if word.lower() in bad_words:
                raise forms.ValidationError(f'Слово {word} не может содержаться в описании продукта')

        return clean_data



class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

class ContactForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'


class ProductModeratorsForm(StyleFormMixin,forms.ModelForm):

    class Meta:
        model = Product
        fields = ('is_published','description','category','owner',)

    def clean_name(self):
        clean_data = self.cleaned_data['name']
        clean_data_words = clean_data.split()
        bad_words = ['казино',
                     'криптовалюта',
                     'крипта',
                     'биржа',
                     'дешево',
                     'бесплатно',
                     'обман',
                     'полиция',
                     'радар']

        for word in clean_data_words:
            if word.lower() in bad_words:
                raise forms.ValidationError(f'Слово {word} не может содержаться в названии продукта')

        return clean_data

    def clean_description(self):
        clean_data = self.cleaned_data['description']
        clean_data_words = clean_data.split()
        bad_words = ['казино',
                     'криптовалюта',
                     'крипта',
                     'биржа',
                     'дешево',
                     'бесплатно',
                     'обман',
                     'полиция',
                     'радар']

        for word in clean_data_words:
            if word.lower() in bad_words:
                raise forms.ValidationError(f'Слово {word} не может содержаться в описании продукта')

        return clean_data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django import template
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from pytils.translit import slugify
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

from catalog.models import Product, Contact, Version, Category
from catalog.forms import ProductForm, ContactForm, VersionForm, ProductModeratorsForm
from catalog.services import get_category_list, get_product_list


# Create your views here.

class ProductListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    extra_context = {'title': 'Каталог продуктов'}

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        actual_versions = Version.objects.filter(actual_version=True)
        context_data['actual_version'] = actual_versions
        context_data['product_list'] = get_product_list()


        return context_data


# @login_required
class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'
    extra_context = {'title': 'Информация о продукте'}


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:home')
    extra_context = {'title': 'Добавление продукта'}

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:home')
    extra_context = {'title': 'Изменение продукта'}

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        elif user.has_perm('can_change_publication_status') and user.has_perm(
                'can_change_description') and user.has_perm('can_change_category'):
            print(self.object.owner)
            print(user)
            return ProductModeratorsForm
        else:

            raise PermissionDenied



class ContactCreateView(CreateView):
    model = Contact
    template_name = 'catalog/contacts.html'
    form_class = ContactForm
    success_url = reverse_lazy('catalog:home')
    extra_context = {'title': 'Добавление контакта'}

class CategoryListView(ListView):
    model = Category
    # template_name = 'catalog/category_list'
    extra_context = {'title': 'Категории продуктов'}


    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category_list'] = get_category_list()

        return context_data

catalog/templates/catalog/base.html
{% load static %}
{% load my_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet"
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"


</head>

<body>
{% include 'includes/inc_main_menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-4 mx-auto text-center">
    <h4 class="display-6">
        <strong>Funny Shop</strong>
    </h4>
    <p class="lead">
        <small>Привет на нашем сайте. Funny Shop - это товары Вашей мечты</small>
    </p>
</div>


<div class="container">
    <div class="row">
        {% block content %}

        {% endblock %}
    </div>
</div>

<div class="container">

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Funny Shop
                <small class="d-block mb-3 text-muted">&copy {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы в соцсетях</a></li>
                    <li><a class="text-muted" href="#">Полезные ссылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>


<script src={% static '/js/bootstrap.bundle.min.js' %}></script>

</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-4 mb-3 mb-sm-0">

    <div class="card">
        <div class="card-body">

            <form method="post">
                {% csrf_token %}
                <p>Вы уверены, что хотите удалить блог "{{ object.header }}"?</p>

                <button type="submit" class="btn btn-danger">Подтверждаю</button>
                <a href="{% url 'catalog:blog_list' %}" class="btn btn-warning">Отменить</a>

                <br>
            </form>
        </div>

    </div>
</div>
</div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.header }}</h4>
        </div>
        <div class="card-body">
            <p> Просмотры: {{ object.views_count }}</p>
            <p><em>{{ object.slug }}</em></p>
            <p>{{ object.content }}</p>
        </div>
    </div>
    <div class="col-6 px-3 py-3 pt-md-3 pb-md-4">
        <img src="/media/{{ object.preview }}" width="150"/>
    </div>

    <br>
    <a href="{% url 'catalog:blog_list' %}" class="btn btn-outline-success">Вернуться в список блогов</a>
</div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<dev>
    <h2 class="my-0 px-3 py-3 pt-md-3 pb-md-4 mr-md-auto font-weight-normal">Блоги</h2>
</dev>

{% for object in object_list %}

<div class="col-sm-4 mb-3 mb-sm-3">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{object.header}}</h4>
            <p class="card-text">{{ object.slug }}</p>
            <p class="card-text">Просмотры: {{ object.views_count }}</p>
            <br>
            <a class="btn btn-outline-success" href="{% url 'catalog:blog_detail' object.pk %}">Подробнее</a>
            <a class="btn btn-outline-success" href="{% url 'catalog:blog_form' object.pk %}">Изменить</a>
            <a class="btn btn-outline-danger" href="{% url 'catalog:blog_confirm_delete' object.pk %}">Удалить</a>

            <br>
        </div>
    </div>
</div>

{% endfor %}
<div>
    <br> <br>
    <a class="btn btn-success" href="blog_form">Создать новую запись в блоге</a>
</div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<dev>
    <h2 class="my-0 px-3 py-3 pt-md-3 pb-md-4 mr-md-auto font-weight-normal">Категории продуктов</h2>
</dev>

{% for object in object_list %}
<div class="col-3">
    <div class="card mx-auto mt-3" style="width: 18rem;">
        <div class="card-body">
            <h4 class="card-title">{{ object.category_name }}</h4>
            <p class="card-text">{{ object.category_description }}</p>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
        </div>
        <div class="card-body">
            <form method="post" action="" class="form-floating">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">Отправить</button>
            </form>
        </div>
    </div>
</div>
<div class="col-lg-9 col-md-6 col-sm-12">
    <!--    <div class="accordion" id="accordionPanelsStayOpenExample">-->

    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h4 class="accordion-header">
                <button class="accordion-button collapsed button-primary form-control" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseOne" aria-expanded="true"
                        aria-controls="flush-collapseOne">
                    Москва (головной офис)
                </button>
            </h4>
            <div id="flush-collapseOne" class="accordion-collapse collapse"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <div class="container text-left">
                        <div class="row align-items-start">
                            <div class="col">
                                Адрес:<br>
                                ул.Монетная, дом 18
                            </div>
                            <div class="col">
                                Директор:<br>
                                Петров Петр Петрович
                            </div>
                            <div class="col">
                                Телефон:<br>
                                +7(999)111-11-11
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h4 class="accordion-header">
                <button class="accordion-button collapsed button-primary form-control" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseTwo" aria-expanded="false"
                        aria-controls="flush-collapseTwo">
                    Санкт-Петербург
                </button>
            </h4>
            <div id="flush-collapseTwo" class="accordion-collapse collapse"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <div class="container text-left">
                        <div class="row align-items-start">
                            <div class="col">
                                Адрес:<br>
                                Постамтский пер., дом 14, офис 1
                            </div>
                            <div class="col">
                                Директор:<br>
                                Кузнецов Иван Петрович
                            </div>
                            <div class="col">
                                Телефон:<br>
                                +7(999)222-22-22
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h4 class="accordion-header">
                <button class="accordion-button collapsed button-primary form-control" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseThree" aria-expanded="false"
                        aria-controls="flush-collapseThree">
                    Краснодар
                </button>
            </h4>
            <div id="flush-collapseThree" class="accordion-collapse collapse"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body">
                    <div class="container text-left">
                        <div class="row align-items-start">
                            <div class="col">
                                Адрес:<br>
                                ул.Красная, дом 4, офис 6
                            </div>
                            <div class="col">
                                Директор:<br>
                                Иванов Иван Иванович
                            </div>
                            <div class="col">
                                Телефон:<br>
                                +7(999)999-99-99
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<dev>
    <h2 class="my-0 px-3 py-3 pt-md-3 pb-md-4 mr-md-auto font-weight-normal">Продукты</h2>
</dev>
<div class="row">
    {% if user.is_authenticated %}
    <div class="col-sm-12 mb-5">
        <a class="btn btn-success" href="{% url 'catalog:product_create' %}">Добавить продукт</a>
    </div>
    {% endif %}

</div>


{% for object in object_list %}

<div class="col-sm-4 mb-3 mb-sm-3">
    <div class="card">
        <div class="card-body">


            <h4 class="card-title">{{object}}</h4>
            <br>

            <p>{{object.description | truncatechars:100}}</p>

            {% for version in actual_version %}
            {% if version.product_id == object.pk %}
            <p>Текущая версия: {{ version }}</p>
            {% endif %}
            {% endfor %}

            <br>
            <div align="right">
                <p class="fs-3"> {{object.price}} руб.</p>

            </div>

            {% if object.image %}
            <img src={{object.image.url | media_filter}} alt="товар" width="100">
            {% endif %}
            <br><br>
            <a href="#" class="btn btn-outline-success">Купить</a>
            <a class="btn btn-outline-success" href="{% url 'catalog:product' object.pk %}">Подробнее</a>
            {% if perms.catalog.change_product or user == object.owner %}
            <a class="btn btn-outline-warning" href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
            {% endif %}

        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-4 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-body">

            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">Категория: {{ product.category }}</p>
            <p class="card-text">Описание: {{ product.description }}</p>
            <p class="card-text">Цена: {{ product.price }} руб.</p>
            <p class="card-text">Запись создана: {{ product.created_at }}</p>
            <p class="card-text">Запись обновлена: {{ product.updated_at }}</p>


            <a href="#" class="btn btn-outline-success">Купить</a>
            {% if perms.catalog.change_product or user == product.owner %}
            <a class="btn btn-outline-warning" href="{% url 'catalog:product_update' object.pk %}">Изменить</a>
            {% endif %}



        </div>
    </div>
</div>
<div class="col-lg-4 col-md-6 col-sm-12">
    <div class="card mb-4 box-shadow">

        <div class="card-body">

            {% if product.image %}
            <img src={{product.image.url | media_filter}} class="rounded mx-auto d-block" alt="товар" width="300">
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-sm-6 mb-3 mb-sm-0">
    <div class="card">
        <div class="card-header">

            <h4 class="card-title">
                {% if object %}
                Изменение продукта
                {% else %}
                Добавление продукта
                {% endif %}

            </h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>

        </div>
        <div class="card-footer">
        </div>
    </div>
</div>
</div>
{% endblock %}